### ISSUE TITLE
Cannot install via ansible galaxy

### ISSUE THREAD

**Issue by farridav** [jaywink/ansible-letsencrypt#28]
When running `ansible-galaxy install ansible-letsencrypt` with `ansible==2.1.1.0` I get
```
- downloading role 'ansible-letsencrypt', owned by
 [WARNING]: - ansible-letsencrypt was NOT installed successfully: Role has no field named u'owner'

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

**Comment by jaywink** [comment]
Thanks for the note, will check this 👍

**Comment by jaywink** [comment]
It looks like this is caused by a confusing repository name possibly? While the repo is called `ansible-letsencrypt` (because I want to prefix roles with `ansible-` :P), the role name is just `letsencrypt`. So the correct name in Galaxy is `jaywink.letsencrypt`, as per [the page](https://galaxy.ansible.com/jaywink/letsencrypt/).

    $ ansible-galaxy install jaywink.letsencrypt
    - downloading role 'letsencrypt', owned by jaywink
    - downloading role from https://github.com/jaywink/ansible-letsencrypt/archive/v0.6.1.tar.gz
    - extracting jaywink.letsencrypt to /etc/ansible/roles/jaywink.letsencrypt
    - jaywink.letsencrypt (v0.6.1) was installed successfully

I think you were just trying to install some other role.

I'll clarify the readme regarding this. Thanks for reporting, let me know if there are still issues!
